/* Automatically generated by './build/bin/build-entry.js' */

import BigDataTable from '../packages/big-data-table/index.js';
import VcTableColumn from '../packages/vc-table-column/index.js';
import Tooltip from '../packages/tooltip/index.js';
import DefaultVideo from '../packages/default-video/index.js';
import LiveVideo from '../packages/live-video/index.js';
import locale from 'vue-creek/src/locale';
import CollapseTransition from 'vue-creek/src/transitions/collapse-transition';

import Utils from '../commons/utils/index.js';

const components = [
  BigDataTable,
  VcTableColumn,
  Tooltip,
  DefaultVideo,
  LiveVideo,
  CollapseTransition
];

const prototypes = [
  Utils
];

const install = function(Vue, opts = {}) {
  locale.use(opts.locale);
  locale.i18n(opts.i18n);

  components.forEach(component => {
    Vue.component(component.name, component);
  });

  prototypes.forEach(prototype => {
    Object.defineProperty(Vue.prototype, prototype.name(), { value: prototype });
  });

  Vue.prototype.$CREEK = {
    size: opts.size || '',
    zIndex: opts.zIndex || 2000
  };

};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '1.0.8',
  locale: locale.use,
  i18n: locale.i18n,
  install,
  CollapseTransition,
  BigDataTable,
  VcTableColumn,
  Tooltip,
  DefaultVideo,
  LiveVideo
};
